### ISSUE TITLE
Add style-check with credo

### ISSUE THREAD

**Issue by certainty** [lasseebert/validation#10]
Since this is a project that is only about to become alive it might be a good point in time
to introduce credo as a style checker. There is not much code yet and adding
this later becomes more and more difficult. 

Should that be wanted I would issue a PR with this https://github.com/lasseebert/validation/compare/master...certainty:add-credo

Another thing that I found useful is using type specs and verify them with dialyzer.
This tends to find quite some problems and allows one to catch them early.

What's your thoughts on this?

**Comment by lasseebert** [comment]
I am totally for credo and type specs :+1: 

I haven't done much type spec'ing myself, so if you could get the project started on that too, it would be much appreciated.

**Comment by lasseebert** [comment]
I added another issue for type specs and dializer: https://github.com/lasseebert/validation/issues/11 ;)

**Comment by certainty** [comment]
Awesome. I am happy to go forward and provide them.

**Comment by lasseebert** [comment]
Closed in https://github.com/lasseebert/validation/pull/17
