### ISSUE TITLE
Nested schemas

### ISSUE THREAD

**Issue by lasseebert** [lasseebert/validation#12]
It should be possible to define nested schemas that can validate nested params.

* Define and apply nested schemas
* Represent nested errors somehow

**Comment by certainty** [comment]
I think this is relatively straight forward. Anything that adheres to the apply protocol should be combinable/nestable. You might want to conditionally apply nested schemas as well. For example when you have tagged data, where the schema of a nested value depends on some other value. 

One thing you have to take care of then is that the errors should be composable too. 

A thing I did is creating a flat error map where the keys where structure that could be passed to `Kernel.get_in` to locate the value that did not validate. Having such a structure is then relatively easy to translate to external representations like JSON pointer.

**Comment by lasseebert** [comment]
Basic support for nested schemas is implemented in #27
