### ISSUE TITLE
White listing

### ISSUE THREAD

**Issue by lasseebert** [lasseebert/validation#14]
This is a discussion about what to do with everything that is not validated.

In some cases it might make sense to just use the list of rules as a white-list, so that everything not defined is discarded.
In other cases it might make sense to treat extra params as an error.
Finally it might make sense to just leave the extra params alone as they are.

**Comment by lasseebert** [comment]
I think we should do like this:

A Schema contains a list of accepted keys, `accepted_keys`. The list defaults the the keys specified by the rules of type "required", "optional" and "value". E.g. all rules that specifies which key they validate.

The Schema is also initialized with a strategy for extra keys, `unknown_key_strategy` that can have one of these three values:
- `:error`: Make the result fail if extra keys are present.
- `:ignore`: Just let the extra keys be.
- `:remove`: Make the schema function as a white-list by removing unknown keys.

IMO `:error` should be the default, since it will be least surprising by failing fast.

**Comment by solnic** [comment]
This should not be a part of validation, this is input pre-processing that may involve coercions too. At least that's how it's done in dry-validation where schema hashes provided by dry-types are used. Currently we sanitize by default by ignoring unspecified keys, but some folks want this to be configurable so ie you can say "I want unspecified keys included in the output too". I think it's fine as there are legitimate cases where it's needed.

**Comment by lasseebert** [comment]
Ok, so if I understand correctly, you say that validation (rules) should not be allowed to change the output, only validate it and add to `errors`. White-listing and coercion is then part of pre-processing.

I like this distinction :+1: 

What do you think of my first "strategy" above. The `:error` strategy that adds errors on unexpected input keys. I think this would be my expectiation of the behaviour of an API. (I like strict APIs :)). That could perhaps just be implemented as a rule.

**Comment by solnic** [comment]
> The :error strategy that adds errors on unexpected input keys. I think this would be my expectiation of the behaviour of an API. (I like strict APIs :)). That could perhaps just be implemented as a rule.

Yes that is a desired feature, we miss it in dry-v and it's gonna be added before 1.0.0

**Comment by lasseebert** [comment]
Right now a schema is build from a list of rules. I think if we build it from a list of rules _and_ a list of (sorted) preprocessors, we would have a nice distinction of concerns. Preprocessors alter the data and rules adds errors.

If we did this, we could actually accept any type of data. E.g. a custom schema could be set up to accept a string of JSON and have a preprocessor parse the JSON before validating it. I don't know if this is a desired feature, though.

**Comment by certainty** [comment]
+1 for being able to somehow whitelist attributes.  
If you decide to go with the preprocessor route it is probably no longer a mere validation library. Not that I am against it. Actually I have the specific use case to validate JSON documents, which would play nicely with this. Just stating this because it may have to be reflected in the name.

**Comment by lasseebert** [comment]
@certainty: I agree that the name should reflect what the library is. I have created an issue for this: https://github.com/lasseebert/validation/issues/18

**Comment by lasseebert** [comment]
~~Waiting for https://github.com/lasseebert/validation/issues/21~~ closed

**Comment by lasseebert** [comment]
Now that preprocessors are in place, I think we should have these three basic kinds of schema behaviours.

* The current `build` has the behaviour of not white listing. Extra keys are ok.
* Second behaviour is white listing according to the given rules. This is implemented by adding a preprocessor based on given rules on build time. The preprocessor simply removes unlisted keys.
* Third behaviour is error'ing on extra attributes, which is implemented by adding a rule based on the given rules on build time.

Note that it should also be possible to build the white-list preprocessor and the "strict" rule without defining a schema.
