### ISSUE TITLE
Add preprocessing

### ISSUE THREAD

**Issue by lasseebert** [lasseebert/validation#21]
For whitelisting and type coercion we need to add preprocessing.

IMO we should then not allow rules to change the input params. They should only be changable by a preprocessor, which might greatly simplify rules. As an example, the order of rules won't matter.

**Comment by lasseebert** [comment]
I started this feature in branch https://github.com/lasseebert/validation/tree/21_preprocessor

**Comment by certainty** [comment]
I agree that separating operations that might change the values and/or the fact that values appear at a certain position leads to a better design. Making rules independent from one another is already a great benefit
