### ISSUE TITLE
Schema function

### ISSUE THREAD

**Issue by lasseebert** [lasseebert/validation#4]
As discussed in #1, we change tactics. Instead of having a schema that is a pure data structure, it is a function combined from other functions. I thought it deserves as issue on its own.

We have these building blocks:

## Result
A `%Result{}` is the thing that a schema returns when applied on a map of input data. It contains the transformed input data (after whitelist and coercion) and error messages.

## Predicate functions

Simple functions that accepts only a value and optionally arguments and returns either `:ok` or `{:error, message}`.

An example would be

```elixir
match? = fn (value, pattern) -> if value =~ pattern, do: :ok, else: {:error, "is invalid"} end
match?.("me@example.com", ~r/@/) # => :ok
match?.("Not an email", ~r/@/)  # => {:error, "is invalid"}
```

Note that a predicate function don't know which key is being tested. We should supply built-in predicates for common use cases, but any (custom) function will do.

### Combining predicate functions

Predicates can be combined into new predicates. Library functions should exist for common combinations such as `and`, `or`, `then`

Example:

```elixir
match? = fn (value, pattern) -> if value =~ pattern, do: :ok, else: {:error, "is invalid"} end
filled? = fn value when value in ["", nil] -> {:error, "must be filled"}; _ -> :ok end
combined = Predicates.and(match?, filled?)
combined.("") # => {:error, "must be filled"}
combined.("Not an email") # => {:error, "is invalid"}
combined.("me@example.com") # => :ok
```

## Rules
A rule is a function that takes as argument a %Result{} and returns an updated result. Higher order library functions should exist to generate these functions.

E.g. a value-validation higher order function might take a key and a predicate is input:

```elixir
rule = value_validation(:name, filled?)
result = %Result{data: %{name: ""}}
rule.(result) # => %Result{data: %{name: ""}, errors: %{name: ["must be filled"]}}
rule.(%)
```

Note that the predicate could also be a combined predicate for more complex rules. Other rule types could also exists. Eg. Key validation (required/optional) or rules that span multiple keys.

## Schema
A schema is a function combined from multiple rules. It takes the input map as argument and returns a `%Result{}`.

It is then possible to do:

```elixir
case schema.(params) do
  %Result{valid?: true, data: data} -> do_something_with(data)
  %Result(errors: errors) -> render_errors(errors)
end
```

Maybe the schema should return `{:ok, result}` or `{:error, result}` instead of having a `valid?` in the result?

**Comment by lasseebert** [comment]
Maybe skip the `%Result{}` and just use `{data, errors}` instead?

**Comment by lasseebert** [comment]
Running the rules in the order they are defined or combined is important. E.g. one could have a coercion rule that changes the keys from strings to atoms and place that rule first.

**Comment by lasseebert** [comment]
Maybe the `%Result{}` should contain both the original input params and the output params? That way rules can whitelist keys by copying data from the former to the latter.

**Comment by certainty** [comment]
@lasseebert do you want to put type coercion into this library? It seems to be a different concern to me. 

Did you already think about on how to represent errors for nested schemas? This had been tricky for me in the past, since one would probably have to have a way to locate the error and also represent such location to the user in a convenient manner.

**Comment by lasseebert** [comment]
@certainty yes, it was originally my intention to put type coercion into the library. I have my doubts if it belongs here, but I think it makes sense for many use cases. E.g. posted forms where all values are strings.

I haven't given much thought to nested schemas yet, but from the top of my head, I think nested errors should be in nested result structs. Then have helper functions to traverse or join them.

**Comment by lasseebert** [comment]
I'll close this issue now since a basic schema is done. I will create other issues where we can discuss coercion, nested schemas and other features.
